export interface Project {
  slug: string;
  title: string;
  level: ProjectLevel;
  dataUsed: string;
  steps: string[];
}

export type ProjectLevel = "Medium" | "High" | "Extreme High" | "Research";

export interface DomainMeta {
  id: string;
  name: string;
  color: string;
  bg: string;
}

export const DOMAIN_META: Record<string, DomainMeta> = {
  population:     { id: "population",     name: "Population Data",     color: "text-cyan-400",    bg: "bg-cyan-400/14" },
  crime:          { id: "crime",          name: "Crime Data",          color: "text-rose-400",    bg: "bg-rose-400/14" },
  education:      { id: "education",      name: "Literacy Rate Data",  color: "text-amber-400",   bg: "bg-amber-400/14" },
  healthcare:     { id: "healthcare",     name: "Healthcare Data",     color: "text-pink-400",    bg: "bg-pink-400/14" },
  agriculture:    { id: "agriculture",    name: "Agriculture Data",    color: "text-emerald-400", bg: "bg-emerald-400/14" },
  economy:        { id: "economy",        name: "Economy Data",        color: "text-yellow-400",  bg: "bg-yellow-400/14" },
  employment:     { id: "employment",     name: "Employment Data",     color: "text-violet-400",  bg: "bg-violet-400/14" },
  environment:    { id: "environment",    name: "Environment Data",    color: "text-green-400",   bg: "bg-green-400/14" },
  climate:        { id: "climate",        name: "Climate Data",        color: "text-sky-400",     bg: "bg-sky-400/14" },
  energy:         { id: "energy",         name: "Energy & Power Data", color: "text-orange-400",  bg: "bg-orange-400/14" },
  pollution:      { id: "pollution",      name: "Pollution Data",      color: "text-purple-400",  bg: "bg-purple-400/14" },
  "wind-pollution":  { id: "wind-pollution",  name: "Wind Pollution Data",  color: "text-teal-400",   bg: "bg-teal-400/14" },
  "water-pollution": { id: "water-pollution", name: "Water Pollution Data", color: "text-blue-400",   bg: "bg-blue-400/14" },
  "land-pollution":  { id: "land-pollution",  name: "Land Pollution Data",  color: "text-emerald-400",bg: "bg-emerald-400/14" },
  "sound-pollution": { id: "sound-pollution", name: "Sound Pollution Data", color: "text-rose-400",   bg: "bg-rose-400/14" },
  "pollution-all":   { id: "pollution-all",   name: "All Pollution Data",   color: "text-purple-400",  bg: "bg-purple-400/14" },
  transportation: { id: "transportation", name: "Transportation Data", color: "text-blue-400",    bg: "bg-blue-400/14" },
  "smart-cities": { id: "smart-cities",  name: "Smart Cities Data",   color: "text-orange-400",  bg: "bg-orange-400/14" },
};

function toSlug(title: string) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const raw: Record<string, { title: string; steps: string[] }[]> = {
  population: [
    { title: "State-wise Population Comparison Dashboard", steps: ["Export state-wise population data from population-open.lovable.app", "Clean and normalize state name columns", "Build comparative bar chart of all states", "Add top-10 / bottom-10 filter toggle", "Deploy as interactive comparison dashboard"] },
    { title: "Gender Split Analysis Across India", steps: ["Download gender-wise population from the census dashboard", "Calculate male/female percentage per state", "Build grouped bar chart for gender split", "Highlight states with highest gender imbalance", "Export findings as CSV report"] },
    { title: "Sex Ratio Ranking by State", steps: ["Pull sex ratio data from population-open.lovable.app", "Rank all states by sex ratio (females per 1000 males)", "Create horizontal bar chart with national average line", "Flag states below 900 sex ratio", "Generate downloadable PDF summary"] },
    { title: "Population Density Choropleth Map", steps: ["Get state-wise population totals from census dashboard", "Merge with state area (sq km) data", "Calculate population density per state", "Render choropleth map with color gradient", "Add tooltip showing state name and density"] },
    { title: "Top 10 Most Populated States Dashboard", steps: ["Export full state population dataset from dashboard", "Sort and extract top 10 states by total population", "Build donut chart showing share of national population", "Add comparison with 2001 census figures", "Deploy with export to Excel feature"] },
    { title: "Urban vs Rural Population Split", steps: ["Download census urban/rural breakdown from dashboard", "Calculate urban percentage per state", "Create stacked bar chart (urban vs rural)", "Identify most urbanized and most rural states", "Build trend comparison with previous census"] },
    { title: "Population Growth Rate by State", steps: ["Pull 2001 and 2011 population from census dashboard", "Calculate decadal growth rate per state", "Rank states by growth rate", "Plot growth rate on India map", "Highlight states exceeding national average growth"] },
    { title: "Child Population 0-6 Age Group Study", steps: ["Filter 0-6 age group data from census dashboard", "Calculate child population percentage per state", "Build bar chart comparing states", "Correlate with sex ratio in 0-6 age group", "Generate insights report with export to PDF"] },
    { title: "Literacy Rate vs Population Correlation", steps: ["Export literacy rate and population data from dashboard", "Plot scatter chart (population vs literacy rate)", "Calculate correlation coefficient", "Identify outlier states", "Build interactive dashboard with drill-down"] },
    { title: "Male vs Female Literacy Gap Analysis", steps: ["Download male and female literacy rates from census", "Calculate literacy gap per state", "Rank states by gender literacy gap", "Create butterfly chart visualization", "Export gap analysis as Excel workbook"] },
    { title: "Census Data Export and Format Converter", steps: ["Use dashboard export to download CSV data", "Build converter tool for CSV to JSON and XLSX", "Add data validation and cleaning pipeline", "Create API endpoint to serve converted data", "Document data schema and publish"] },
    { title: "Population Pyramid by Age Group", steps: ["Extract age-group breakdown from census dashboard", "Separate male and female counts per age bracket", "Build population pyramid chart", "Add state selector for comparison", "Deploy interactive pyramid visualization"] },
    { title: "Scheduled Caste and Tribe Population Map", steps: ["Pull SC/ST population data from census dashboard", "Calculate SC/ST percentage per state", "Build choropleth map with dual layers", "Compare with national SC/ST average", "Link to welfare scheme coverage data"] },
    { title: "Least Populated States and UTs Dashboard", steps: ["Export population data and filter smallest states/UTs", "Build ranked bar chart of bottom 10 by population", "Add area and density comparison", "Show growth trends for small states", "Deploy as mini-dashboard with PDF export"] },
    { title: "State Population Trend Forecasting", steps: ["Download decadal census data from dashboard", "Calculate annual growth rate estimates", "Train simple projection model for 2021-2031", "Visualize projections with confidence bands", "Build interactive forecast dashboard"] },
  ],
  crime: [
    { title: "State-wise Crime Rate Comparison", steps: ["Download NCRB annual report CSV", "Normalize crime counts by population", "Rank states by crime rate", "Build interactive bar chart", "Add year filter"] },
    { title: "Telangana District Crime Heatmap", steps: ["Get district-level NCRB data", "Map to GeoJSON boundaries", "Color by crime frequency", "Add crime type dropdown filter", "Deploy map dashboard"] },
    { title: "Crime Against Women Analysis", steps: ["Filter women-related crime categories", "Track trends 2015-2023", "Identify top 10 states", "Compare urban vs rural rates", "Generate awareness report"] },
    { title: "Cybercrime Growth Tracker", steps: ["Extract cybercrime rows from NCRB", "Plot year-on-year growth", "Break down by category (fraud, hacking)", "Map state-wise incidents", "Highlight emerging hotspots"] },
    { title: "Police-to-Population Ratio Study", steps: ["Get sanctioned vs actual police strength", "Calculate ratio per lakh population", "Rank states by deficit", "Correlate with crime rates", "Publish policy brief"] },
    { title: "Juvenile Crime Trend Analysis", steps: ["Filter juvenile offender data", "Track age group distribution", "Compare across states", "Correlate with dropout rates", "Suggest intervention points"] },
    { title: "Murder Rate District Dashboard", steps: ["Extract murder/IPC 302 data", "Normalize per lakh population", "Rank top 20 districts", "Add 5-year trend line", "Build alert threshold system"] },
    { title: "Road Accident Fatality Map", steps: ["Download MORTH accident data", "Map fatalities by highway stretch", "Identify black spots", "Overlay traffic volume data", "Propose safety interventions"] },
    { title: "Drug-Related Offences Tracker", steps: ["Extract NDPS Act case data", "Map seizure hotspots by district", "Track year-wise trends", "Correlate with border districts", "Build monitoring dashboard"] },
    { title: "Prison Occupancy and Under-trial Study", steps: ["Get NCRB prison statistics", "Calculate overcrowding ratio", "Identify states with highest under-trial %", "Map against judicial vacancy data", "Generate reform report"] },
    { title: "Domestic Violence Reporting Trends", steps: ["Extract domestic violence case data from NCRB", "Track year-on-year reporting changes", "Map state-wise reporting rates", "Correlate with helpline call data", "Build awareness gap dashboard"] },
    { title: "Crime Clearance Rate Analysis", steps: ["Download case disposal data from NCRB", "Calculate clearance rate per crime type", "Rank states by conviction efficiency", "Identify bottlenecks in judicial process", "Generate police performance report"] },
    { title: "Property Crime Hotspot Mapping", steps: ["Filter theft, burglary, robbery data", "Map hotspot districts on India map", "Calculate per capita property crime rate", "Track seasonal patterns", "Build predictive alert system"] },
    { title: "Crime Rate vs Urbanization Correlation", steps: ["Merge NCRB crime data with census urban %", "Plot scatter chart for correlation", "Identify outlier districts", "Run regression analysis", "Publish research-grade report"] },
    { title: "Human Trafficking Case Tracker", steps: ["Extract human trafficking data from NCRB", "Map origin and destination states", "Track rescue and conviction statistics", "Correlate with border and migration data", "Build NGO coordination dashboard"] },
  ],
  education: [
    { title: "State-wise Literacy Rate Dashboard", steps: ["Download state literacy tables from census sources", "Clean male, female, and total literacy columns", "Rank states by overall literacy rate", "Build comparative bar chart with national average", "Publish an interactive literacy dashboard"] },
    { title: "District Literacy Ranking Map", steps: ["Extract district-wise literacy rates", "Join literacy data with district boundary files", "Render choropleth map by literacy band", "Highlight top and bottom 25 districts", "Add district tooltip and export option"] },
    { title: "Male vs Female Literacy Gap Analysis", steps: ["Split literacy rates by gender", "Calculate gender literacy gap per state", "Rank states by widest and narrowest gaps", "Create butterfly chart visualization", "Export gender-gap summary as Excel workbook"] },
    { title: "Rural vs Urban Literacy Split", steps: ["Collect rural and urban literacy indicators", "Calculate rural-urban gap by state", "Build stacked comparison charts", "Identify states with high rural lag", "Prepare policy-ready summary notes"] },
    { title: "Literacy Rate vs Population Correlation", steps: ["Merge population totals with literacy rate data", "Plot state-wise scatter chart", "Calculate correlation coefficient", "Flag outlier states and districts", "Build interactive drill-down view"] },
    { title: "Female Literacy Improvement Tracker", steps: ["Collect historical female literacy rates", "Calculate decadal improvement by state", "Rank fastest-improving regions", "Compare against national progress", "Generate trend dashboard and CSV export"] },
    { title: "Youth Literacy Rate Study", steps: ["Filter youth literacy indicators from census and survey data", "Compare rates by state and gender", "Identify low-literacy youth clusters", "Map priority districts", "Publish intervention brief"] },
    { title: "Literacy and School Access Correlation", steps: ["Merge literacy rates with school access indicators", "Calculate access-to-literacy relationship", "Plot district-level scatter charts", "Identify regions where access is not translating to literacy", "Write insight report"] },
    { title: "Literacy Gap by Social Group", steps: ["Extract literacy indicators by social group", "Normalize categories across states", "Calculate group-wise gaps", "Map vulnerable regions", "Build equity-focused dashboard"] },
    { title: "Adult Literacy Campaign Tracker", steps: ["Collect adult literacy program coverage data", "Compare coverage with low-literacy districts", "Track progress across years", "Flag underserved adult learner groups", "Create monitoring dashboard"] },
    { title: "Literacy Rate Forecasting Model", steps: ["Compile historical literacy rates", "Calculate annualized improvement trends", "Train simple projection model", "Forecast 2031 literacy rates by state", "Visualize forecast confidence bands"] },
    { title: "Literacy Rate Data Quality Audit", steps: ["Profile missing and inconsistent literacy records", "Validate state and district names", "Check rate bounds and gender totals", "Create cleaned data dictionary", "Publish reproducible audit report"] },
    { title: "Lowest Literacy Districts Priority Index", steps: ["Select literacy, gender gap, and population indicators", "Normalize each indicator", "Score districts by literacy priority", "Map high-priority regions", "Document methodology and recommendations"] },
    { title: "Literacy Dashboard Export Converter", steps: ["Export literacy dashboard data as CSV", "Build converter for JSON and XLSX output", "Add validation for percentage fields", "Create downloadable district summaries", "Document schema for reuse"] },
    { title: "Literacy and Employment Readiness Study", steps: ["Merge literacy rates with labour indicators", "Compare literacy and workforce participation", "Identify high-literacy low-employment regions", "Run state-level correlation analysis", "Publish research-ready findings"] },
  ],
  healthcare: [
    { title: "Public Hospital Bed Availability Map", steps: ["Download NHP facility data", "Calculate beds per 1000 population", "Map district-wise availability", "Identify critical shortage zones", "Build live dashboard"] },
    { title: "Infant Mortality Rate Analysis", steps: ["Extract IMR from NFHS dataset", "Compare state-wise rates", "Track decline 2015-2021", "Correlate with immunization coverage", "Generate health report"] },
    { title: "Immunization Coverage Dashboard", steps: ["Get HMIS immunization data", "Calculate full immunization %", "Map district-wise coverage", "Identify cold chain gaps", "Track monthly progress"] },
    { title: "Disease Burden by State", steps: ["Download ICMR disease registry", "Rank top 10 diseases per state", "Plot incidence per lakh", "Add year-wise trend lines", "Build comparative dashboard"] },
    { title: "Doctor-to-Population Ratio Study", steps: ["Get NMC registered doctor data", "Calculate ratio per 10,000 population", "Rank states by shortage", "Compare urban vs rural", "Map health worker deserts"] },
    { title: "Maternal Mortality Rate Tracker", steps: ["Extract MMR data from SRS", "Track trend 2005-2020", "Map state-wise rates", "Correlate with institutional delivery %", "Set SDG target progress markers"] },
    { title: "Malnutrition in Children Dashboard", steps: ["Get NFHS stunting/wasting data", "Map under-5 malnutrition by district", "Compare 2015 vs 2021 NFHS rounds", "Identify persistent hotspots", "Link to POSHAN scheme data"] },
    { title: "Mental Health Facility Coverage", steps: ["Download NIMHANS facility data", "Calculate psychiatrist-to-population ratio", "Map district gaps", "Compare urban vs rural access", "Propose facility expansion plan"] },
    { title: "TB Notification and Treatment Tracker", steps: ["Get NIKSHAY TB case data", "Track notification rate per lakh", "Calculate treatment success %", "Map high-burden districts", "Monitor Ni-kshay Poshan Yojana reach"] },
    { title: "Health Insurance Coverage Analysis", steps: ["Extract Ayushman Bharat data", "Calculate beneficiary coverage %", "Map empanelled hospitals by district", "Track claims and settlements", "Identify coverage gaps"] },
    { title: "Blood Bank Availability Map", steps: ["Download NACO/SBTC blood bank directory", "Map blood banks by district", "Calculate blood units available per lakh population", "Identify districts with zero blood banks", "Build emergency supply dashboard"] },
    { title: "Ambulance Response Time Study", steps: ["Get 108/102 ambulance call data", "Calculate average response time by district", "Map response time heatmap", "Identify black zones with over 30 min response", "Propose ambulance station placement"] },
    { title: "COVID-19 Vaccination Progress Tracker", steps: ["Download CoWIN vaccination data", "Calculate dose coverage by state and age group", "Map first vs second dose gaps", "Track booster uptake trends", "Build vaccination equity dashboard"] },
    { title: "Primary Health Centre Infrastructure Audit", steps: ["Get IPHS compliance data for PHCs", "Calculate infrastructure score per facility", "Map PHCs lacking essential equipment", "Compare state-wise PHC readiness", "Generate facility upgrade priority list"] },
    { title: "Telemedicine Adoption and Reach Study", steps: ["Get eSanjeevani teleconsultation data", "Track adoption rate by state and month", "Map districts with highest usage", "Calculate teleconsultation per doctor ratio", "Build digital health access dashboard"] },
  ],
  agriculture: [
    { title: "Crop Yield Comparison Dashboard", steps: ["Download ICAR crop production CSV", "Normalize yield per hectare", "Compare top 5 crops per state", "Add year-wise trend lines", "Build interactive chart"] },
    { title: "Rainfall vs Crop Production Analysis", steps: ["Merge IMD rainfall and crop data", "Calculate correlation coefficient", "Map drought-prone districts", "Overlay with MSP data", "Publish climate-agriculture report"] },
    { title: "Farmer Suicide Data Analysis", steps: ["Get NCRB farmer distress data", "Normalize by farming population", "Map hotspot districts", "Correlate with debt and rainfall", "Generate policy brief"] },
    { title: "Soil Health Card Coverage Tracker", steps: ["Download SHC portal data", "Calculate cards issued vs target", "Map state-wise completion %", "Track nutrient deficiency patterns", "Build monitoring dashboard"] },
    { title: "Agricultural Market Price Tracker", steps: ["Get Agmarknet daily price data", "Track modal price for key commodities", "Plot seasonal price trends", "Compare mandis across states", "Build price alert system"] },
    { title: "Irrigation Coverage Analysis", steps: ["Extract net irrigated area data", "Calculate % of cultivable land irrigated", "Map canal vs groundwater split", "Identify irrigation-deficit districts", "Propose investment priority map"] },
    { title: "PM-KISAN Beneficiary Tracking", steps: ["Download PM-KISAN payment data", "Calculate beneficiary coverage per state", "Track instalment disbursements", "Map pending vs completed payments", "Identify exclusion errors"] },
    { title: "Cold Storage Infrastructure Map", steps: ["Get NHB cold storage directory", "Map capacity by state and district", "Calculate storage per ton of produce", "Identify horticulture deficit zones", "Link to wastage reduction data"] },
    { title: "Fertiliser Consumption Trends", steps: ["Download FAI fertiliser data", "Track NPK usage per hectare", "Compare state-wise imbalances", "Correlate with soil health data", "Generate sustainable use report"] },
    { title: "Crop Insurance Claim Analysis", steps: ["Get PMFBY claims dataset", "Calculate claim settlement ratio", "Map districts with high rejection rates", "Track premium vs payout trends", "Identify scheme improvements"] },
    { title: "Organic Farming Adoption Tracker", steps: ["Download PKVY/organic certification data", "Map certified organic area by state", "Calculate organic vs conventional yield", "Track year-wise adoption growth", "Identify high-potential districts"] },
    { title: "Horticulture Production Dashboard", steps: ["Get NHM horticulture production data", "Track fruit and vegetable output by state", "Calculate per capita horticulture production", "Map export-oriented clusters", "Build seasonal availability calendar"] },
    { title: "Agricultural Credit Flow Analysis", steps: ["Download NABARD credit disbursement data", "Calculate credit flow per hectare by state", "Track KCC (Kisan Credit Card) issuance", "Map credit gap districts", "Generate financial inclusion report"] },
    { title: "Land Use and Cropping Pattern Study", steps: ["Get Directorate of Economics data on land use", "Map net sown area vs fallow land by state", "Track cropping intensity trends", "Identify shifting crop patterns", "Build land utilization dashboard"] },
    { title: "Food Grain Storage and Wastage Monitor", steps: ["Download FCI storage capacity data", "Calculate storage deficit by state", "Track post-harvest loss estimates", "Map godown utilization rates", "Propose storage expansion priorities"] },
  ],
  economy: [
    { title: "State GDP Growth Dashboard", steps: ["Download MoSPI GSDP data", "Calculate year-on-year growth", "Rank states by GSDP", "Plot sectoral contribution", "Build comparison dashboard"] },
    { title: "GST Collection Tracker", steps: ["Get GSTN monthly collection data", "Track state-wise trends", "Calculate per capita collection", "Map compliance rate", "Build revenue alert system"] },
    { title: "FDI Inflow by State and Sector", steps: ["Download DPIIT FDI data", "Map top destination states", "Break down by sector", "Track quarterly trends", "Compare pre/post policy changes"] },
    { title: "Public Expenditure Analysis", steps: ["Get Union Budget expenditure data", "Break down by ministry", "Calculate per capita spending", "Track capital vs revenue split", "Compare 5-year trends"] },
    { title: "Inflation and CPI Tracker", steps: ["Download RBI/MoSPI CPI data", "Track food vs non-food inflation", "Map rural vs urban CPI", "Correlate with MSP changes", "Build monthly dashboard"] },
    { title: "Banking Access and Financial Inclusion", steps: ["Get RBI branch density data", "Calculate branches per lakh population", "Map unbanked districts", "Track Jan Dhan account growth", "Identify credit gap areas"] },
    { title: "MSME Registration and Growth Tracker", steps: ["Download Udyam registration data", "Map MSME count by district", "Break down by sector and size", "Track employment generation", "Identify growth corridors"] },
    { title: "Export-Import Trade Analysis", steps: ["Get DGCIS trade statistics", "Identify top export commodities", "Map port-wise trade volumes", "Track trade deficit trends", "Build commodity dashboard"] },
    { title: "Poverty Headcount Index Study", steps: ["Get NITI Aayog MPI data", "Map multidimensional poverty by district", "Compare 2015 vs 2021 scores", "Identify worst-performing districts", "Link to scheme coverage data"] },
    { title: "State Debt and Fiscal Health Monitor", steps: ["Download RBI state finance data", "Calculate debt-to-GSDP ratio", "Track fiscal deficit trends", "Rank states by financial health", "Generate risk assessment"] },
    { title: "UPI Transaction Volume Dashboard", steps: ["Download NPCI UPI statistics", "Track monthly transaction volume and value", "Map adoption by state", "Calculate per capita digital transactions", "Build fintech growth dashboard"] },
    { title: "Foreign Exchange Reserves Tracker", steps: ["Get RBI weekly forex reserve data", "Track composition (gold, SDR, foreign currency)", "Plot reserve trend over 10 years", "Correlate with rupee exchange rate", "Build macroeconomic stability dashboard"] },
    { title: "Startup Ecosystem Growth Analysis", steps: ["Download DPIIT recognized startup data", "Map startup density by state and city", "Break down by industry sector", "Track funding stage distribution", "Build startup ecosystem ranking"] },
    { title: "Retail Inflation Basket Analysis", steps: ["Get MoSPI CPI item-wise weight data", "Track price changes across food basket items", "Compare rural vs urban basket weights", "Identify highest-contributing inflation items", "Build consumer price alert dashboard"] },
    { title: "State Revenue Receipts Comparison", steps: ["Download CAG state finance audit data", "Calculate own tax vs central transfers ratio", "Rank states by fiscal self-sufficiency", "Track revenue diversification trends", "Generate state fiscal health report"] },
  ],
  employment: [
    { title: "Unemployment Rate by State", steps: ["Get PLFS employment data", "Calculate unemployment rate", "Break down by age and gender", "Track quarterly trends", "Map state-wise variations"] },
    { title: "Urban Employment Sector Analysis", steps: ["Extract urban employment data", "Break down by industry", "Calculate formal vs informal split", "Track year-wise shifts", "Build sector dashboard"] },
    { title: "MGNREGS Work Demand Tracker", steps: ["Download MGNREGS MIS data", "Track job card vs work demanded", "Calculate days provided per household", "Map district-wise utilization", "Identify demand-supply gaps"] },
    { title: "Gig Economy Worker Study", steps: ["Collect e-Shram registration data", "Map gig worker distribution", "Break down by platform type", "Calculate income bracket distribution", "Propose social security coverage"] },
    { title: "Women Labour Force Participation", steps: ["Get PLFS LFPR data for women", "Track urban vs rural FLFPR", "Compare state-wise trends", "Correlate with education levels", "Build gender gap dashboard"] },
    { title: "Skill Development Outcomes Tracker", steps: ["Download PMKVY training data", "Calculate placement rate by sector", "Map training centres by district", "Track certification to job conversion", "Identify high-performing schemes"] },
    { title: "Youth Unemployment Analysis", steps: ["Filter PLFS data for age 15-29", "Calculate youth unemployment rate", "Map state-wise hotspots", "Correlate with education completion", "Propose targeted interventions"] },
    { title: "Wage Growth by Industry", steps: ["Get PLFS weekly earnings data", "Calculate real wage growth", "Compare organized vs unorganized sector", "Map regional wage gaps", "Track minimum wage compliance"] },
    { title: "Contract vs Permanent Employment Ratio", steps: ["Extract ASI factory employment data", "Calculate contract worker percentage", "Track industry-wise trends", "Map states with high contract ratio", "Link to labour law compliance data"] },
    { title: "Construction Sector Workforce Study", steps: ["Get BOCW registration data", "Calculate registered vs estimated workers", "Map state-wise welfare fund utilization", "Track accident and compensation data", "Identify coverage gaps"] },
    { title: "Government Job Vacancy Tracker", steps: ["Scrape SSC, UPSC, and state PSC vacancy data", "Track sanctioned vs filled positions by ministry", "Calculate vacancy rate trends", "Map department-wise shortfalls", "Build recruitment pipeline dashboard"] },
    { title: "Apprenticeship and Internship Dashboard", steps: ["Download NAPS apprenticeship portal data", "Track enrolled vs completed apprenticeships", "Map by sector and state", "Calculate employer participation rate", "Build skills-to-jobs pipeline report"] },
    { title: "Self-Employment and Entrepreneurship Study", steps: ["Get Mudra Yojana loan disbursement data", "Track Shishu/Kishore/Tarun category breakdown", "Map self-employment density by district", "Calculate loan repayment rates", "Build micro-enterprise growth dashboard"] },
    { title: "Migrant Worker Employment Tracker", steps: ["Extract inter-state migration data from PLFS", "Map worker flows between states", "Calculate sector-wise migrant employment", "Track wage differentials for migrants", "Build migrant welfare monitoring dashboard"] },
    { title: "IT and Services Sector Employment Trends", steps: ["Get NASSCOM and MeitY IT employment data", "Track headcount growth in IT/BPO/GCC sectors", "Map tech hub employment concentrations", "Calculate attrition and hiring trends", "Build tech employment forecast dashboard"] },
  ],
  environment: [
    { title: "AQI City Dashboard", steps: ["Download CPCB AQI daily data", "Calculate annual average per city", "Map cities by pollution level", "Track seasonal variation", "Build real-time alert system"] },
    { title: "Forest Cover Change Analysis", steps: ["Get FSI India State of Forest report data", "Calculate net forest cover change", "Map gain vs loss by state", "Correlate with deforestation drivers", "Build decade comparison"] },
    { title: "River Water Quality Tracker", steps: ["Download CPCB river monitoring data", "Track BOD and DO levels", "Map polluted river stretches", "Identify industrial discharge hotspots", "Build pollution trend dashboard"] },
    { title: "Groundwater Depletion Study", steps: ["Get CGWB groundwater data", "Map over-exploited blocks", "Track water table decline", "Correlate with irrigation patterns", "Propose recharge zone priorities"] },
    { title: "Plastic Waste Generation Map", steps: ["Get CPCB SWM data", "Calculate plastic waste per capita", "Map ULBs with high generation", "Track processing capacity vs generation", "Identify disposal gaps"] },
    { title: "Soil Contamination Assessment", steps: ["Collect soil quality and contamination records", "Map heavy metal and chemical risk by district", "Compare with land-use categories", "Flag high-risk industrial zones", "Build remediation priority dashboard"] },
    { title: "Biodiversity Hotspot Map", steps: ["Collect protected area and species habitat data", "Map biodiversity hotspots by state", "Track pressure from land-use change", "Identify conservation priority zones", "Publish biodiversity dashboard"] },
    { title: "Industrial Pollution Compliance Monitor", steps: ["Download CPCB consent data", "Map non-compliant industries", "Track violation trends", "Calculate penalty recovery rate", "Build compliance dashboard"] },
    { title: "Wetland and Biodiversity Tracker", steps: ["Get Wildlife Institute wetland data", "Map Ramsar sites and status", "Track encroachment incidents", "Correlate with migratory bird data", "Build conservation monitoring tool"] },
    { title: "Carbon Emission by State", steps: ["Get INCCA emission inventory", "Calculate per capita emissions", "Break down by sector", "Track reduction against NDC targets", "Build net-zero progress dashboard"] },
    { title: "Noise Pollution Monitoring Dashboard", steps: ["Download CPCB noise level data for major cities", "Map industrial, commercial, and residential zones", "Track violations above permissible limits", "Correlate with health impact data", "Build noise violation alert system"] },
    { title: "E-Waste Generation and Recycling Tracker", steps: ["Get CPCB e-waste inventory data", "Calculate per capita e-waste generation", "Map authorized recyclers by state", "Track collection vs target rates", "Identify recycling capacity gaps"] },
    { title: "Coastal Erosion and Sea Level Monitor", steps: ["Get NCCR coastal vulnerability data", "Map erosion-prone stretches by state", "Track annual shoreline change rate", "Correlate with mangrove cover data", "Build coastal risk assessment dashboard"] },
    { title: "Urban Green Space and Tree Cover Index", steps: ["Get FSI tree cover outside forest data", "Calculate green space per capita by city", "Map cities below WHO recommended levels", "Track green cover change over decades", "Build urban greening priority index"] },
    { title: "Environmental Compliance Scorecard", steps: ["Collect consent, inspection, and violation records", "Score compliance by sector and state", "Track repeat violations", "Map enforcement gaps", "Build compliance scorecard"] },
  ],
  climate: [
    { title: "State-wise Climate Risk Dashboard", steps: ["Collect IMD rainfall and temperature indicators", "Normalize climate risk signals", "Rank states by composite risk", "Build comparative risk dashboard", "Add CSV export for project use"] },
    { title: "Rainfall Variability Analysis", steps: ["Download long-term rainfall records", "Calculate monthly and annual variability", "Compare monsoon deviation by state", "Plot rainfall anomaly charts", "Publish district-level summary"] },
    { title: "Heatwave Frequency Tracker", steps: ["Extract heatwave event data", "Count heatwave days by district", "Compare trends across years", "Map high-exposure regions", "Create alert-threshold dashboard"] },
    { title: "Drought Vulnerability Map", steps: ["Merge rainfall deficit and crop exposure data", "Calculate drought vulnerability score", "Map vulnerable districts", "Identify recurring drought zones", "Generate intervention priority list"] },
    { title: "Flood Event Impact Dashboard", steps: ["Collect flood event and rainfall data", "Map affected districts", "Track frequency and severity over time", "Compare with population exposure", "Build flood-risk dashboard"] },
    { title: "Temperature Trend by State", steps: ["Download historical temperature series", "Calculate annual average trend", "Compare warming rates by region", "Plot state-wise trend lines", "Export visual report"] },
    { title: "Climate Risk vs Agriculture Yield", steps: ["Merge climate indicators with crop yield data", "Calculate sensitivity by crop and state", "Identify vulnerable crops", "Plot risk-yield correlation", "Prepare adaptation insights"] },
    { title: "Coastal Climate Exposure Study", steps: ["Collect cyclone, sea-level, and coastal district data", "Score coastal exposure", "Map high-risk coastline districts", "Compare with population density", "Build coastal resilience brief"] },
    { title: "Extreme Weather Event Timeline", steps: ["Compile floods, droughts, heatwaves, and cyclones", "Standardize event dates and locations", "Build searchable timeline", "Add filters by state and event type", "Publish dashboard with exports"] },
    { title: "Climate Adaptation Priority Index", steps: ["Select heat, flood, drought, and exposure indicators", "Normalize each metric", "Create composite priority score", "Rank districts by adaptation need", "Document methodology and caveats"] },
  ],
  energy: [
    { title: "State-wise Energy Consumption Dashboard", steps: ["Download power consumption data from POSOCO", "Calculate per capita consumption by state", "Map industrial vs residential usage", "Track renewable vs thermal split", "Build energy efficiency dashboard"] },
    { title: "Solar Power Installation Tracker", steps: ["Get MNRE solar rooftop data", "Map installed capacity by district", "Track subsidy disbursement status", "Calculate generation vs consumption", "Identify high-potential regions"] },
    { title: "Wind Energy Potential Map", steps: ["Download NIWE wind resource data", "Map wind speed zones by state", "Compare installed vs potential capacity", "Track capacity addition trends", "Build investment priority dashboard"] },
    { title: "Thermal Power Plant Emissions Analysis", steps: ["Get CPCB emission data for power plants", "Calculate CO2 and particulate emissions", "Map plants by pollution levels", "Track compliance with norms", "Generate environmental impact report"] },
    { title: "Rural Electrification Progress Tracker", steps: ["Download DDUGJY scheme data", "Map electrified vs unelectrified villages", "Track household connection rates", "Identify quality of supply issues", "Build access monitoring dashboard"] },
    { title: "Power Distribution Loss Analysis", steps: ["Get state DISCOM AT&C loss data", "Calculate transmission and distribution losses", "Rank states by loss percentage", "Correlate with financial health of utilities", "Propose reduction interventions"] },
    { title: "Electric Vehicle Charging Infrastructure", steps: ["Download FAME II charging station data", "Map stations by highway and city", "Calculate coverage per 100 km", "Track utilization rates", "Identify expansion priority zones"] },
    { title: "Hydropower Project Status Dashboard", steps: ["Get CEA hydropower project data", "Track under-construction projects", "Map installed capacity by river basin", "Calculate generation vs potential", "Build project monitoring system"] },
    { title: "Smart Meter Deployment Tracker", steps: ["Download smart meter installation data", "Map coverage by state and utility", "Track billing efficiency improvements", "Calculate consumer adoption rates", "Build deployment progress dashboard"] },
    { title: "Grid Integration of Renewables Study", steps: ["Get renewable integration data from NLDC", "Track solar and wind grid penetration", "Map curtailment by region", "Analyze grid stability challenges", "Propose infrastructure upgrades"] },
    { title: "Battery Storage Capacity Dashboard", steps: ["Collect grid-scale storage project data", "Map battery capacity by state", "Track commissioned and planned projects", "Compare storage with renewable capacity", "Build storage readiness dashboard"] },
    { title: "DISCOM Financial Health Monitor", steps: ["Download DISCOM finance indicators", "Track AT&C loss and subsidy dependence", "Rank utilities by financial risk", "Compare tariff and collection efficiency", "Build utility health scorecard"] },
    { title: "Energy Access Reliability Study", steps: ["Collect outage and supply quality data", "Calculate reliability by district", "Map low-reliability regions", "Compare rural and urban supply", "Publish energy access report"] },
    { title: "Renewable Purchase Obligation Tracker", steps: ["Collect RPO compliance data", "Compare obligation and achievement by state", "Track renewable certificate usage", "Flag underperforming utilities", "Build compliance dashboard"] },
    { title: "Green Hydrogen Project Map", steps: ["Collect announced green hydrogen projects", "Map capacity, location, and sector", "Track project stage and investment", "Compare with renewable availability", "Create emerging energy dashboard"] },
  ],
  "wind-pollution": [
    { title: "National Air Quality Index Dashboard", steps: ["Download CPCB AQI daily data from environmentdash.lovable.app", "Clean and normalize city-level columns", "Map cities by pollution level on the dashboard", "Track seasonal variation of PM2.5 and PM10", "Use the dashboard to verify real-time alerts"] },
    { title: "Industrial Air Pollution Tracker", steps: ["Get industrial emission records from environmentdash.lovable.app", "Filter by non-compliant factory sectors", "Map factory coordinates and violation frequencies", "Calculate penalty recovery rates on the dashboard", "Export clean compliance logs"] },
    { title: "Construction Dust Pollution Monitor", steps: ["Collect city construction violation records from environmentdash.lovable.app", "Identify dust complaint hotspots", "Compare complaints with PM10 readings on the dashboard", "Track local enforcement actions", "Use the dashboard to build a dust-control priority list"] },
    { title: "Vehicle Emission Hotspot Study", steps: ["Merge traffic volume and air quality data using environmentdash.lovable.app", "Identify high-emission urban corridors", "Compare peak-hour pollution levels on the dashboard", "Map target intervention zones", "Generate transport pollution brief"] },
    { title: "Crop Burning Smoke Dispersion Map", steps: ["Import agricultural fire coordinates from environmentdash.lovable.app", "Overlay wind direction trends on the map", "Model smoke dispersion pathways on the dashboard", "Estimate AQI impact on downwind cities", "Export daily advisory warnings"] },
    { title: "Indoor Air Quality in Urban Schools", steps: ["Retrieve classroom PM2.5 sensor feeds from environmentdash.lovable.app", "Analyze air exchange rates during school hours", "Compare classroom levels with traffic peak hours on the dashboard", "Design real-time ventilation prompts", "Publish policy recommendations"] },
    { title: "Urban Green Belt PM2.5 Impact Study", steps: ["Filter forest and tree cover records using environmentdash.lovable.app", "Compare PM2.5 levels inside vs outside green belts", "Calculate dust absorption indices on the dashboard", "Overlay canopy density with urban zones", "Draft city forestry greening guidelines"] },
    { title: "Thermal Inversion and Winter Smog Analysis", steps: ["Extract altitude temperature records from environmentdash.lovable.app", "Correlate thermal inversion frequency with AQI spikes", "Analyze diurnal smog build-up rates on the dashboard", "Assess humidity impact on pollutant suspension", "Publish winter smog safety guides"] },
    { title: "Meteorology-Based AQI Forecast Model", steps: ["Acquire wind speed and relative humidity history from environmentdash.lovable.app", "Analyze clearing rate of suspended pollutants", "Train AQI prediction models on the dashboard", "Visualize forecasted vs actual parameters", "Register forecasting API endpoint"] },
    { title: "Methane Emission Detection Map", steps: ["Acquire satellite methane concentration feeds via environmentdash.lovable.app", "Pinpoint gas pipeline and landfill leak coordinates", "Track monthly leak volume changes on the dashboard", "Cross-reference leaks with population grids", "Export methane hazard audit report"] },
    { title: "Ultra-fine Particulate Matter Distribution", steps: ["Extract PM1.0 monitoring parameters from environmentdash.lovable.app", "Track geographic distribution patterns in industrial parks", "Compare particle size distribution ratios on the dashboard", "Correlate PM1.0 with public exposure indices", "Draft fine-particle audit report"] },
    { title: "Sulfur Dioxide Industrial Plume Tracker", steps: ["Download industrial SO2 stack emission records from environmentdash.lovable.app", "Map high-volume emission stacks across power plants", "Trace plume direction using weather layers on the dashboard", "Calculate acid rain risk indices", "Publish industrial emission brief"] },
    { title: "Coastal Sea Breeze AQI Mitigation Study", steps: ["Collect coastal city hourly wind-direction records from environmentdash.lovable.app", "Compare diurnal breeze cycles with pollutant levels", "Map dispersion zones during onshore breeze on the dashboard", "Analyze harbor emission accumulation", "Draft port-city wind zoning guides"] },
    { title: "Ammonia Concentration and Fertilizer Cycles", steps: ["Extract rural atmospheric ammonia levels from environmentdash.lovable.app", "Correlate ammonia spikes with seasonal sowing schedules", "Map agricultural fertilizer intensity grids on the dashboard", "Identify chemical run-off dispersion paths", "Publish rural air safety brief"] },
    { title: "Carbon Monoxide Urban Traffic Corridor Audit", steps: ["Download municipal CO sensor logs from environmentdash.lovable.app", "Identify corridors exceeding safe exposure limits", "Correlate CO levels with signal wait times on the dashboard", "Map high-density vehicle choke points", "Export transport air clean strategy"] },
  ],
  "water-pollution": [
    { title: "River Water Quality Monitoring", steps: ["Download CPCB river monitoring data from environmentdash.lovable.app", "Track BOD and DO levels across river basins", "Map polluted river stretches on the dashboard", "Identify industrial discharge hotspots", "Use the dashboard to verify water quality trends"] },
    { title: "Groundwater Contamination Study", steps: ["Download CGWB groundwater quality data from environmentdash.lovable.app", "Filter by nitrate and fluoride contamination", "Map contaminated blocks on the dashboard", "Trace contamination sources near agricultural zones", "Export water safety guidelines"] },
    { title: "Coastal Water Quality Analysis", steps: ["Get NCCR coastal water data from environmentdash.lovable.app", "Map pollution levels along the shoreline", "Track industrial discharge points on the dashboard", "Evaluate marine ecosystem impact indicators", "Export coastal health reports"] },
    { title: "Lake Pollution Restoration Dashboard", steps: ["Collect lake water quality parameters from environmentdash.lovable.app", "Track dissolved oxygen and nutrient loading", "Map lake restoration progress on the dashboard", "Compare pollution sources across urban lakes", "Build restoration progress index"] },
    { title: "Heavy Metals in Reservoirs Mapping", steps: ["Download reservoir chemical compositions from environmentdash.lovable.app", "Map lead, arsenic, and mercury occurrences", "Calculate toxicity exposure quotients on the dashboard", "Track seasonal purification efficiency levels", "Export water safety warnings"] },
    { title: "Microplastics in Estuarine Systems", steps: ["Acquire estuarine water sample analysis data from environmentdash.lovable.app", "Map microplastic particle density by river mouth", "Correlate with surrounding industrial activity on the dashboard", "Compare seasonal microplastic concentrations", "Generate conservation report"] },
    { title: "Rainwater Harvesting Contamination Risk", steps: ["Gather rooftop runoff water quality samples from environmentdash.lovable.app", "Measure chemical and bacterial contaminants", "Evaluate risk by roofing material type on the dashboard", "Develop filtration system recommendations", "Build harvesting safety dashboard"] },
    { title: "Agricultural Runoff Eutrophication Tracker", steps: ["Collect river nitrogen and phosphorus levels from environmentdash.lovable.app", "Map agricultural crop types and fertilizer use", "Identify algal bloom occurrences via satellite on the dashboard", "Correlate fertilizer cycles with bloom dates", "Publish runoff control brief"] },
    { title: "Industrial Wastewater Discharge Auditor", steps: ["Download factory effluent monitoring records from environmentdash.lovable.app", "Compare discharge parameters against CPCB limits", "Map repeat offending factories by estate on the dashboard", "Calculate cumulative discharge volume", "Build compliance warning dashboard"] },
    { title: "Sewage Treatment Plant Efficiency Map", steps: ["Get inlet and outlet BOD/COD data for STPs from environmentdash.lovable.app", "Calculate pollutant removal efficiency per plant", "Map plants operating below design capacity on the dashboard", "Correlate with river water quality downgradient", "Create STP performance scorecard"] },
    { title: "Groundwater Fluoride Exposure Map", steps: ["Extract fluoride concentration records from environmentdash.lovable.app", "Identify districts exceeding permissible fluoride limits", "Correlate with skeletal fluorosis statistics on the dashboard", "Map deep-bore well water hazards", "Draft community filtration recommendations"] },
    { title: "Aquifer Recharge Salinity Intrusion Tracker", steps: ["Download coastal aquifer electrical conductivity logs from environmentdash.lovable.app", "Map groundwater salinity intrusion boundaries", "Track intrusion rates against extraction volumes on the dashboard", "Identify critical fresh-saline transition zones", "Export aquifer protection guidelines"] },
    { title: "Thermal Pollution in Thermal Plant Discharge", steps: ["Get water temperature logs from power plant outfalls using environmentdash.lovable.app", "Map mixing zones in receiving river basins", "Evaluate biological oxygen depletion profiles on the dashboard", "Analyze impact on local fish habitats", "Publish thermal discharge audit report"] },
    { title: "Pesticide Accumulation in Wetlands", steps: ["Download pesticide residue wetland monitoring logs from environmentdash.lovable.app", "Map organochlorine and organophosphate levels", "Correlate concentrations with bird sanctuary buffers on the dashboard", "Track seasonal wetland water levels", "Export habitat toxicological briefs"] },
    { title: "Mining Effluent Acid Mine Drainage Map", steps: ["Collect mine water discharge pH and heavy metal levels from environmentdash.lovable.app", "Map drainage routes near major coal and iron mines", "Calculate stream neutralization capacity on the dashboard", "Identify affected municipal drinking intakes", "Publish acid mine drainage report"] },
  ],
  "land-pollution": [
    { title: "Landfill and Waste Dump Mapping", steps: ["Download CPCB solid waste data from environmentdash.lovable.app", "Map landfill sites and dump yards by state", "Calculate capacity vs utilization on the dashboard", "Track leachate contamination risks", "Use the dashboard to identify urgent remediation zones"] },
    { title: "Plastic Waste Generation Tracker", steps: ["Get city plastic waste metrics from environmentdash.lovable.app", "Calculate per capita plastic generation", "Compare processing capacity vs generation on the dashboard", "Identify recycling and disposal gaps", "Export plastic waste scorecard"] },
    { title: "Hazardous Waste Management Dashboard", steps: ["Download hazardous waste logs from environmentdash.lovable.app", "Map generation by manufacturing sector", "Track recycling vs incineration on the dashboard", "Verify facility compliance rates", "Build industrial waste monitor"] },
    { title: "Urban Slum Sanitation Mapping", steps: ["Download SBM urban sanitation data from environmentdash.lovable.app", "Map slums with low toilet access", "Compare sanitation scores with water access on the dashboard", "Track waste collection frequencies", "Identify high-risk sanitation zones"] },
    { title: "Biomedical Waste Facility Mapping", steps: ["Download state biomedical waste treatment data from environmentdash.lovable.app", "Map common treatment facilities against hospital density", "Track incinerator chimney height compliance on the dashboard", "Calculate daily untreated waste volumes", "Export state compliance reports"] },
    { title: "E-Waste Dismantling Center Audit", steps: ["Get registered e-waste collection center coordinates from environmentdash.lovable.app", "Map formal recycling capacity against estimated city generation", "Overlay locations with informal metal-recovery hubs on the dashboard", "Analyze toxic heavy metal soil traces near centers", "Export e-waste audit scorecard"] },
    { title: "Heavy Metals Soil Contamination Index", steps: ["Collect soil quality logs around industrial areas from environmentdash.lovable.app", "Calculate soil contamination index for zinc, lead, chromium", "Map contaminated fields by distance from source on the dashboard", "Correlate with local food crop sampling", "Generate remediation scorecard"] },
    { title: "Pesticide Residue in Agricultural Soil", steps: ["Download organic carbon and pesticide residue soil logs from environmentdash.lovable.app", "Identify zones with pesticide accumulation above norms", "Correlate with local groundwater contamination levels on the dashboard", "Overlay with crop type history", "Draft sustainable farming map"] },
    { title: "Fly Ash Dump Site Environmental Risk", steps: ["Map coal fly ash dykes and dump locations using environmentdash.lovable.app", "Track historical breach and leakage events", "Calculate soil and air exposure in neighboring villages on the dashboard", "Monitor post-closure stabilization progress", "Build dyke stability dashboard"] },
    { title: "Industrial Sludge Disposal Monitor", steps: ["Gather ETP sludge generation data from manufacturing plants using environmentdash.lovable.app", "Map authorized landfill disposal manifests", "Track volume of hazardous sludge transported on the dashboard", "Identify gaps in disposal records", "Create sludge transport audit tool"] },
    { title: "Oil Spill Land Contamination Tracker", steps: ["Get pipeline burst and oil spill location logs from environmentdash.lovable.app", "Map soil degradation boundaries around spill sites", "Track cleanup progress and bioremediation success on the dashboard", "Measure hydrocarbon concentrations in adjacent topsoil", "Export pipeline safety warning map"] },
    { title: "Open Defecation Free (ODF) Verification Map", steps: ["Download ODF+ and ODF++ village audit scores from environmentdash.lovable.app", "Map villages with persistent open defecation cases", "Correlate ODF status with child stunting rates on the dashboard", "Track public toilet maintenance feedback", "Publish village sanitation leaderboard"] },
    { title: "Electronic Scrap Lead Leaching Study", steps: ["Retrieve acid rain pH and soil lead concentration logs from environmentdash.lovable.app", "Map scrap storage yards near residential boundaries", "Analyze lead leaching depth under rainy weather on the dashboard", "Correlate with shallow well water contamination", "Draft battery recycling zone guidelines"] },
    { title: "Fertilizer Salinity and Soil Hardening Tracker", steps: ["Download agricultural soil electric conductivity records from environmentdash.lovable.app", "Map soil hardening zones across irrigated plains", "Analyze chemical sodium saturation rates on the dashboard", "Track organic manure applications", "Publish soil health restoration map"] },
    { title: "Quarry Dust Land Degradation Map", steps: ["Import stone quarry boundary coordinates from environmentdash.lovable.app", "Map vegetative cover degradation around quarry sites", "Analyze dust settling density on surrounding farmland on the dashboard", "Correlate with crop yield reductions", "Export quarry zone remediation brief"] },
  ],
  "sound-pollution": [
    { title: "Noise Pollution Hotspot Analysis", steps: ["Get SPCB noise monitoring data from environmentdash.lovable.app", "Map noise levels by commercial and residential zones", "Track decibel limit violations on the dashboard", "Identify high-traffic noise hotspots", "Use the dashboard to generate city noise reports"] },
    { title: "Silent Zone Noise Violation Monitor", steps: ["Gather decibel log data near hospitals and schools from environmentdash.lovable.app", "Track daytime and nighttime silent zone limit breaches", "Map peak violation hours on the dashboard", "Identify key contributing traffic sources", "Export silent zone compliance scorecards"] },
    { title: "Traffic Noise vs Urban Greenery Buffer", steps: ["Collect highway decibel profiles from environmentdash.lovable.app", "Compare sound levels across different green buffer widths", "Analyze sound dampening effectiveness on the dashboard", "Map low-buffer highway segments", "Draft acoustic planning guidelines"] },
    { title: "Airport Flight Path Noise Impact Map", steps: ["Gather flight path noise logs from environmentdash.lovable.app", "Map residential zones under active flight corridors", "Correlate noise peaks with flight schedules on the dashboard", "Identify neighborhoods exceeding safe night noise limits", "Generate airport noise exposure map"] },
    { title: "Festive Season Decibel Violation Tracker", steps: ["Collect decibel monitoring records during major festivals from environmentdash.lovable.app", "Compare festival noise levels against base year records", "Map regions with highest decibel limits breach on the dashboard", "Track time-limit compliance for loudspeakers", "Create festival noise dashboard"] },
    { title: "Metro Construction Sound Emission Study", steps: ["Log construction site noise levels near residential blocks using environmentdash.lovable.app", "Evaluate compliance with night construction norms", "Compare sound levels before and after acoustic barrier install on the dashboard", "Track citizen noise complaints", "Publish construction noise brief"] },
    { title: "Industrial Area Perimeter Noise Audit", steps: ["Download factory boundary decibel survey records from environmentdash.lovable.app", "Identify plants exceeding daytime industrial noise limits", "Map compliance status by manufacturing sector on the dashboard", "Track corrective silencer installation rates", "Build perimeter noise audit tool"] },
    { title: "Railway Corridor Acoustic Barrier Study", steps: ["Log decibel peaks during train passage near cities using environmentdash.lovable.app", "Estimate noise propagation by distance from track", "Model effectiveness of noise barrier walls on the dashboard", "Map high-exposure residential clusters", "Generate railway acoustic report"] },
    { title: "Commercial Street Night Noise Tracker", steps: ["Get decibel logger records for commercial markets after 10 PM from environmentdash.lovable.app", "Identify noise contribution from generators and music", "Map streets violating nighttime noise caps on the dashboard", "Track enforcement officer visits", "Build night noise compliance dashboard"] },
    { title: "Honking Frequency Mapping at Intersections", steps: ["Deploy acoustic cameras at busy city intersections using environmentdash.lovable.app", "Count honks per minute under varying traffic densities", "Map highest-intensity honking intersections on the dashboard", "Correlate honking with wait time at traffic lights", "Build no-honking priority index"] },
    { title: "Metro Rail Underground Vibration Impact", steps: ["Gather geological vibration and noise logs near heritage structures using environmentdash.lovable.app", "Map seismic velocity amplitudes under train passage", "Track structural movement indicators on the dashboard", "Correlate transit frequency with vibrations", "Export underground vibration safety report"] },
    { title: "Generator Set Acoustic Enclosure Map", steps: ["Import generator decibel ratings from telecom tower audits using environmentdash.lovable.app", "Map compliance of towers with acoustic enclosure rules", "Track diesel exhaust emissions against noise levels on the dashboard", "Flag non-compliant commercial complexes", "Export generator noise audit map"] },
    { title: "Marine Acoustic Noise in Deepwater Harbors", steps: ["Download underwater hydrophone decibel logs from environmentdash.lovable.app", "Map vessel traffic paths and ship engine noise profiles", "Track impact of harbor dredging on marine life on the dashboard", "Identify whale-shipping route conflicts", "Publish harbor acoustic protection map"] },
    { title: "Wind Turbine Blade Low-Frequency Noise", steps: ["Gather low-frequency infrasound logs near wind farms using environmentdash.lovable.app", "Map sound pressure levels against wind velocity and direction", "Track sleep-disturbance feedback from surrounding villages on the dashboard", "Model turbine buffer distance scenarios", "Export wind farm acoustic zones"] },
    { title: "Acoustic Camera Illegal Siren Tracking", steps: ["Retrieve siren frequency audio records from city intersections using environmentdash.lovable.app", "Map unauthorized VIP siren use coordinates", "Track police response and penalty challans on the dashboard", "Analyze siren peak hours", "Publish siren abuse city report"] },
  ],
  transportation: [
    { title: "Railway Network Coverage Map", steps: ["Download IR station and route data", "Map rail connectivity by district", "Calculate rail density per 1000 sq km", "Identify unconnected districts", "Build rail access dashboard"] },
    { title: "Road Accident Black Spot Analysis", steps: ["Get MORTH accident data", "Identify high-frequency accident locations", "Map by highway and state", "Calculate fatality rate per stretch", "Propose safety interventions"] },
    { title: "National Highway Development Tracker", steps: ["Download NHAI project data", "Map completed vs ongoing projects", "Track lane expansion progress", "Calculate cost per km", "Build project monitoring dashboard"] },
    { title: "Public Transport Ridership Study", steps: ["Get state transport corporation data", "Track bus ridership trends", "Calculate route profitability", "Map underserved corridors", "Propose network optimization"] },
    { title: "Airport Connectivity Analysis", steps: ["Download AAI passenger data", "Map airports by traffic volume", "Calculate tier-2/3 city connectivity", "Track UDAN scheme coverage", "Identify connectivity gaps"] },
    { title: "Freight Movement Dashboard", steps: ["Get IR freight loading statistics", "Track commodity-wise movement", "Map major freight corridors", "Calculate modal share of rail vs road", "Build logistics efficiency index"] },
    { title: "EV Charging Infrastructure Map", steps: ["Download BEE/MoP charging station data", "Map stations by state and highway", "Calculate coverage per 100 km", "Track monthly additions", "Identify expansion priority zones"] },
    { title: "Metro Rail Usage Tracker", steps: ["Get DMRC/metro authority ridership data", "Track daily average ridership", "Map station-wise footfall", "Calculate cost recovery ratio", "Compare cities by efficiency"] },
    { title: "Toll Collection Revenue Analysis", steps: ["Download NHAI toll plaza data", "Calculate daily collection per plaza", "Track FASTag adoption rate", "Map revenue by highway corridor", "Identify evasion hotspots"] },
    { title: "Inland Waterway Traffic Study", steps: ["Get IWAI traffic statistics", "Map active NW routes", "Track cargo movement trends", "Calculate cost vs rail/road", "Identify expansion potential"] },
    { title: "Vehicle Registration Growth Dashboard", steps: ["Download VAHAN vehicle registration data", "Track EV vs ICE registration trends", "Map vehicle density per 1000 population", "Break down by vehicle type", "Build transport demand forecasting model"] },
    { title: "Port Traffic and Capacity Analysis", steps: ["Get IPA major port traffic data", "Track cargo throughput trends", "Map port capacity utilization rates", "Compare turnaround times across ports", "Build maritime logistics dashboard"] },
    { title: "State Highway Condition Assessment", steps: ["Download road condition survey data from NHAI/PMGSY", "Calculate good/fair/poor road percentage by state", "Map pothole and damage complaint hotspots", "Track maintenance spending vs road condition", "Build road quality index dashboard"] },
    { title: "Last-Mile Connectivity Analysis", steps: ["Get PMGSY rural road data", "Calculate habitations connected vs target", "Map unconnected villages by state", "Track all-weather road completion", "Build rural connectivity gap dashboard"] },
    { title: "Aviation Fuel and Emission Tracker", steps: ["Get DGCA airline fuel consumption data", "Calculate CO2 emissions per passenger-km", "Track fuel efficiency trends by airline", "Map busiest route emissions", "Build sustainable aviation dashboard"] },
  ],
  "smart-cities": [
    { title: "Smart City Mission Progress Tracker", steps: ["Download SCM project dashboard data", "Track completed vs ongoing projects", "Map city-wise fund utilization", "Calculate project completion rate", "Build city performance index"] },
    { title: "Integrated Command Centre Coverage", steps: ["Get ICCC deployment data", "Map cities with operational ICCCs", "Track services integrated", "Calculate citizen service response time", "Build smart governance score"] },
    { title: "Smart Street Lighting Dashboard", steps: ["Download LED street light data", "Calculate energy savings per city", "Map coverage percentage", "Track maintenance response time", "Build ROI calculator"] },
    { title: "Solid Waste Management Index", steps: ["Get SWM scores from MoHUA survey", "Rank cities by waste processing", "Map door-to-door collection coverage", "Track wet vs dry segregation", "Build clean city index"] },
    { title: "Digital Payments Adoption Map", steps: ["Get RBI digital payment data", "Calculate transactions per capita", "Map UPI adoption by city tier", "Track merchant onboarding", "Build fintech penetration index"] },
    { title: "Smart Water Metering Study", steps: ["Download AMRUT smart meter data", "Map cities with metered connections", "Calculate NRW (non-revenue water) ratio", "Track billing efficiency", "Identify improvement areas"] },
    { title: "Urban Heat Island Analysis", steps: ["Get satellite land surface temperature data", "Compare urban vs peri-urban temps", "Map heat island zones", "Correlate with green cover data", "Propose cooling interventions"] },
    { title: "Public Wi-Fi Hotspot Coverage", steps: ["Download PM-WANI hotspot data", "Map PDOs by city and ward", "Calculate coverage per sq km", "Track active connections", "Identify digital desert zones"] },
    { title: "Citizen Grievance Resolution Tracker", steps: ["Get 311/CPGRAMS complaint data", "Calculate resolution rate by category", "Track average resolution time", "Map wards with high complaint volume", "Build service quality index"] },
    { title: "Smart Parking and Traffic Management", steps: ["Download city smart parking data", "Map parking utilization by zone", "Calculate revenue vs capacity", "Track traffic signal coordination", "Build congestion prediction model"] },
    { title: "CCTV Surveillance Coverage Analysis", steps: ["Get city-wise CCTV installation data", "Calculate cameras per sq km by zone", "Map blind spots and coverage gaps", "Track camera uptime and maintenance", "Build public safety coverage dashboard"] },
    { title: "Smart Bus and Transit System Tracker", steps: ["Download city smart transit data", "Track GPS-enabled bus fleet percentage", "Map real-time passenger information system coverage", "Calculate on-time performance metrics", "Build transit efficiency comparison dashboard"] },
    { title: "Municipal Revenue and Expenditure Dashboard", steps: ["Get ULB financial data from MoHUA", "Track own-source revenue vs grants", "Calculate per capita municipal spending", "Map cities by financial self-sufficiency", "Build municipal fiscal health index"] },
    { title: "Swachh Bharat Urban Score Tracker", steps: ["Download Swachh Survekshan ranking data", "Track city rank changes over years", "Map ODF (Open Defecation Free) status", "Calculate waste processing improvement rate", "Build cleanliness progress dashboard"] },
    { title: "Smart Electricity Grid and Metering Study", steps: ["Get DISCOM smart meter deployment data", "Track smart meter coverage by city", "Calculate AT and C loss reduction from smart metering", "Map prepaid vs postpaid smart meter adoption", "Build energy efficiency monitoring dashboard"] },
  ],
};

const research: Record<string, { title: string; steps: string[] }[]> = {
  population: [
    { title: "Migration and Urbanization Research Study", steps: ["Collect census migration tables", "Classify origin and destination states", "Calculate urban migration share", "Model drivers of migration", "Publish research summary with charts"] },
    { title: "Ageing Population Policy Research", steps: ["Extract age-wise population tables", "Calculate elderly dependency ratio", "Map states with rapid ageing", "Compare health and pension indicators", "Write policy recommendations"] },
    { title: "Demographic Dividend Research Report", steps: ["Combine working-age population data with education data", "Calculate state-wise demographic dividend window", "Compare employment readiness indicators", "Rank states by opportunity", "Prepare research-grade report"] },
    { title: "Household Size and Fertility Research", steps: ["Download household composition data", "Compare average household size by state", "Correlate with fertility and literacy indicators", "Identify regional patterns", "Create academic-style findings note"] },
    { title: "Population Vulnerability Index", steps: ["Select density, dependency, literacy, and urbanization indicators", "Normalize each indicator", "Build composite vulnerability score", "Map state-wise index values", "Document methodology and limitations"] },
  ],
  crime: [
    { title: "Crime Reporting Bias Research", steps: ["Collect NCRB reporting and disposal data", "Compare reported crime with literacy and urbanization", "Identify possible under-reporting patterns", "Run correlation analysis", "Publish caveats and findings"] },
    { title: "Gender Safety Index Research", steps: ["Select women safety crime indicators", "Normalize rates by population", "Combine with policing and conviction indicators", "Rank states by composite score", "Prepare research methodology note"] },
    { title: "Cybercrime Vulnerability Study", steps: ["Extract cybercrime categories by state", "Merge with internet penetration indicators", "Calculate cybercrime rate per user base", "Identify high-growth states", "Write risk assessment report"] },
    { title: "Judicial Delay and Crime Outcomes", steps: ["Collect case disposal and conviction data", "Calculate pending case ratio", "Compare with crime clearance rate", "Identify justice delivery bottlenecks", "Build evidence-backed research brief"] },
    { title: "Urban Crime Pattern Research", steps: ["Merge city crime and urban population data", "Classify crimes by category", "Compare metro and non-metro patterns", "Detect outlier cities", "Publish urban safety insights"] },
  ],
  education: [
    { title: "Literacy Inequality Research", steps: ["Collect district literacy indicators", "Compare gender, rural, urban, and social-group gaps", "Identify inequality clusters", "Correlate with population and access indicators", "Write research report"] },
    { title: "Gender Literacy Gap Research", steps: ["Extract male and female literacy rates", "Calculate gender gap trends", "Map districts with persistent gaps", "Compare with social and economic indicators", "Publish policy note"] },
    { title: "Digital Literacy Access Research", steps: ["Use digital access and literacy proxy indicators", "Compare rural and urban access", "Correlate with literacy outcomes", "Identify priority districts", "Prepare digital inclusion report"] },
    { title: "Adult Literacy Vulnerability Study", steps: ["Collect adult literacy and demographic data", "Calculate adult literacy risk indicators", "Rank districts by intervention need", "Compare with program coverage", "Document actionable findings"] },
    { title: "Literacy and Social Equity Research", steps: ["Use literacy tables by gender and social category", "Compare gaps across states", "Identify underserved groups", "Model equity risk factors", "Write research-grade conclusion"] },
  ],
  healthcare: [
    { title: "Health Access Inequality Research", steps: ["Collect facility and population data", "Calculate access indicators by district", "Compare rural and urban availability", "Map underserved regions", "Publish equity findings"] },
    { title: "Maternal Health Outcomes Study", steps: ["Extract MMR and institutional delivery indicators", "Compare changes over time", "Correlate with PHC availability", "Identify lagging states", "Prepare policy research brief"] },
    { title: "Disease Burden and Socioeconomic Risk", steps: ["Collect disease incidence data", "Merge with poverty and sanitation indicators", "Run state-wise comparison", "Identify vulnerable clusters", "Write evidence summary"] },
    { title: "Public Health Infrastructure Readiness", steps: ["Use hospital, PHC, and staff availability data", "Score districts on readiness indicators", "Map infrastructure gaps", "Compare with population pressure", "Document methodology"] },
    { title: "Vaccination Equity Research", steps: ["Download vaccination coverage data", "Compare coverage by region and age group", "Identify low-coverage pockets", "Correlate with access indicators", "Publish recommendations"] },
  ],
  agriculture: [
    { title: "Climate Risk and Crop Yield Research", steps: ["Merge rainfall and yield datasets", "Calculate rainfall variability", "Compare yield sensitivity by crop", "Identify climate-vulnerable districts", "Write research report"] },
    { title: "Farmer Income and Market Access Study", steps: ["Collect crop price and production data", "Estimate state-wise market realization", "Map mandi access indicators", "Compare income risk patterns", "Prepare policy brief"] },
    { title: "Irrigation Equity Research", steps: ["Use irrigation coverage data", "Compare canal, groundwater, and rainfed areas", "Identify irrigation-deficit regions", "Correlate with yield outcomes", "Publish findings"] },
    { title: "Soil Health and Fertiliser Use Study", steps: ["Merge soil health and fertiliser consumption data", "Calculate nutrient imbalance indicators", "Map high-risk districts", "Compare with crop productivity", "Write sustainability note"] },
    { title: "Crop Diversification Research", steps: ["Collect crop area data over time", "Calculate diversification index", "Compare states and agro-climatic zones", "Identify monoculture risk", "Build research summary"] },
  ],
  economy: [
    { title: "Regional Economic Inequality Research", steps: ["Collect GSDP and population data", "Calculate per capita income gaps", "Compare long-term trends", "Identify convergence or divergence", "Publish economic research note"] },
    { title: "Fiscal Health Risk Study", steps: ["Use state finance and debt data", "Calculate fiscal pressure indicators", "Rank states by risk", "Compare expenditure priorities", "Write research conclusions"] },
    { title: "Digital Payments Adoption Research", steps: ["Collect UPI and banking access data", "Calculate per capita transaction indicators", "Compare urbanization and adoption", "Identify low-adoption regions", "Publish fintech insights"] },
    { title: "Inflation Impact Research", steps: ["Use CPI and consumption basket data", "Compare rural and urban inflation pressure", "Identify high-impact categories", "Assess state-level exposure", "Prepare policy brief"] },
    { title: "MSME Growth and Employment Study", steps: ["Merge MSME registration and employment indicators", "Map enterprise density", "Compare sector-wise growth", "Identify regional clusters", "Write research-grade report"] },
  ],
  employment: [
    { title: "Youth Employment Transition Research", steps: ["Collect PLFS youth employment data", "Compare education-to-work transition rates", "Map high-risk states", "Correlate with skill training data", "Publish intervention brief"] },
    { title: "Women Workforce Participation Study", steps: ["Use PLFS LFPR data", "Compare rural and urban participation", "Correlate with education and safety indicators", "Identify barriers by state", "Write research findings"] },
    { title: "Informal Employment Vulnerability Index", steps: ["Extract formal and informal job indicators", "Normalize vulnerability metrics", "Build composite index by state", "Map high-risk sectors", "Document methodology"] },
    { title: "Migration and Labour Market Research", steps: ["Collect migration and employment datasets", "Map worker flows by state", "Compare wage differences", "Identify destination-sector patterns", "Prepare research report"] },
    { title: "Skill Training Outcome Research", steps: ["Download PMKVY and placement data", "Calculate training-to-placement conversion", "Compare sectors and states", "Identify program gaps", "Publish evidence summary"] },
  ],
  environment: [
    { title: "Environmental Quality Research Index", steps: ["Select air, water, forest, waste, and biodiversity indicators", "Normalize district-level environmental signals", "Build composite quality score", "Map high-risk regions", "Write methodology report"] },
    { title: "Air Pollution Health Risk Study", steps: ["Merge AQI and health outcome data", "Calculate exposure categories", "Compare city-level risk", "Identify seasonal patterns", "Prepare public health research brief"] },
    { title: "Water Stress and Agriculture Research", steps: ["Use groundwater and crop datasets", "Map over-exploited regions", "Compare irrigation dependence", "Assess crop risk exposure", "Publish policy recommendations"] },
    { title: "Forest Change and Development Study", steps: ["Collect forest cover change data", "Compare with district development indicators", "Identify gain and loss regions", "Analyze trade-off patterns", "Write research findings"] },
    { title: "Waste Management Capacity Research", steps: ["Use solid waste and recycling capacity data", "Calculate processing gap by city", "Compare with population pressure", "Identify priority cities", "Publish urban environment brief"] },
  ],
  climate: [
    { title: "Long-term Climate Trend Research", steps: ["Collect multi-decade temperature and rainfall data", "Calculate state-wise trend slopes", "Compare regional climate signals", "Assess uncertainty and limitations", "Write research findings"] },
    { title: "Heat Risk and Urban Exposure Study", steps: ["Merge heatwave records with urban population data", "Calculate exposure by city and district", "Identify vulnerable urban regions", "Compare mitigation indicators", "Publish heat-risk brief"] },
    { title: "Monsoon Reliability Research", steps: ["Analyze monsoon onset, withdrawal, and rainfall totals", "Calculate reliability metrics by state", "Compare dry and wet years", "Map high-variability regions", "Prepare climate planning note"] },
    { title: "Climate Disaster Vulnerability Study", steps: ["Combine flood, drought, cyclone, and heat indicators", "Normalize disaster exposure metrics", "Rank districts by vulnerability", "Compare with resilience indicators", "Publish research dashboard"] },
    { title: "Climate Adaptation Readiness Research", steps: ["Select adaptation spending and risk indicators", "Compare readiness against climate exposure", "Identify high-risk low-readiness districts", "Create policy priority matrix", "Write research-grade conclusion"] },
  ],
  energy: [
    { title: "Renewable Energy Transition Research", steps: ["Collect solar, wind, hydro, and thermal capacity data", "Calculate renewable share by state", "Compare capacity growth over time", "Identify transition leaders and laggards", "Publish energy transition brief"] },
    { title: "Power Reliability and Access Study", steps: ["Merge outage, electrification, and consumption data", "Compare reliability across districts", "Identify underserved regions", "Assess rural and urban differences", "Write access research note"] },
    { title: "DISCOM Loss Reduction Research", steps: ["Collect AT&C loss and billing efficiency data", "Rank utilities by loss intensity", "Compare reforms and performance", "Identify high-risk utilities", "Publish utility reform findings"] },
    { title: "Clean Energy Investment Readiness", steps: ["Select renewable potential, grid access, and policy indicators", "Normalize readiness metrics", "Rank states by investment readiness", "Map priority energy corridors", "Document methodology"] },
    { title: "Energy Demand Forecast Study", steps: ["Use historical consumption and economic indicators", "Estimate demand growth by sector", "Compare state-level demand patterns", "Build forecast scenarios", "Prepare research-grade conclusion"] },
  ],
  "wind-pollution": [
    { title: "Air Pollution Health Risk Research", steps: ["Export AQI and health outcome records from environmentdash.lovable.app", "Calculate exposure categories per city", "Compare regional health risk patterns on the dashboard", "Assess seasonal health correlations", "Write public health research conclusion"] },
    { title: "Coal Plant Emission Policy Research", steps: ["Collect fly ash and flue gas desulfurization logs from environmentdash.lovable.app", "Evaluate state compliance rates against national norms", "Compare emissions before and after retrofits on the dashboard", "Model health benefits of stricter enforcement", "Draft national power plant clean air policy brief"] },
    { title: "Dust Storm Impact Mitigation Study", steps: ["Download trans-boundary dust storm timeline records from environmentdash.lovable.app", "Trace storm trajectories across northern plains", "Compare city-level PM10 spikes on the dashboard", "Analyze soil moisture mitigation effects", "Draft sandstorm early warning framework"] },
    { title: "Air Quality Index Standard Calibration", steps: ["Download international and national AQI scoring grids from environmentdash.lovable.app", "Compare health warnings across different thresholds", "Analyze city compliance metrics under strict standards on the dashboard", "Run sensitivity analysis on sub-indices", "Publish calibration research recommendations"] },
    { title: "Urban Heat Island Air Quality Nexus", steps: ["Retrieve surface temperature and ozone concentration logs from environmentdash.lovable.app", "Map temperature differences between concrete and green zones", "Correlate heat anomalies with ozone formation on the dashboard", "Model cooling buffer benefit scenarios", "Publish heat-AQI mitigation study"] },
  ],
  "water-pollution": [
    { title: "Water Pollution Burden Research", steps: ["Extract river and groundwater quality logs from environmentdash.lovable.app", "Score cumulative pollution burden per basin", "Identify municipal waste hotspots on the dashboard", "Run correlation with urban density indicators", "Write water quality research brief"] },
    { title: "Ganges River Pollution Health Nexus", steps: ["Download multi-year fecal coliform records from environmentdash.lovable.app", "Map gastrointestinal disease incidents in riverfront towns", "Correlate pollution peaks with hospital admissions on the dashboard", "Model healthcare costs of river degradation", "Publish riverine epidemiological paper"] },
    { title: "Wetland Conservation Policy Review", steps: ["Get Ramsar site encroachment and water quality data from environmentdash.lovable.app", "Compare state wetland conservation budgets", "Assess policy implementation gaps on the dashboard", "Model bird population trends vs water cleanliness", "Draft wetland conservation policy proposals"] },
    { title: "Pharmaceutical Residues in Urban Rivers", steps: ["Extract antibiotic and NSAID water concentration logs from environmentdash.lovable.app", "Map pharmaceutical hotspots near drug manufacturing hubs", "Analyze antibiotic resistance gene prevalence on the dashboard", "Evaluate wastewater treatment limits", "Publish aquatic pharmacology research paper"] },
    { title: "Urban Water Supply Vulnerability Index", steps: ["Download municipal raw water quality indices from environmentdash.lovable.app", "Calculate safety margins for treatment plants", "Map supply networks vulnerable to source contamination on the dashboard", "Model emergency backup source scenarios", "Publish water security index study"] },
  ],
  "land-pollution": [
    { title: "Industrial Pollution Compliance Study", steps: ["Export compliance and inspection logs from environmentdash.lovable.app", "Rank manufacturing sectors by non-compliance", "Map repeat offender locations on the dashboard", "Compare penalties vs corrective action rates", "Publish compliance research findings"] },
    { title: "Municipal Solid Waste Processing Gaps", steps: ["Download waste generation and processing logs from environmentdash.lovable.app", "Calculate processing gap per million-plus city", "Model landfill expansion rates on the dashboard", "Assess socio-economic cost of dumping", "Write waste management policy brief"] },
    { title: "Soil Bioremediation Policy Research", steps: ["Get records of bioremediation pilots on heavy metal sites from environmentdash.lovable.app", "Compare costs of phytoremediation vs soil excavation", "Assess policy funding frameworks on the dashboard", "Model scale-up timelines across contaminated zones", "Draft national bioremediation policy recommendations"] },
    { title: "Plastic Ban Enforcement Impact Analysis", steps: ["Retrieve single-use plastic seizure records from environmentdash.lovable.app", "Map enforcement raids across state borders", "Correlate plastic imports with ban timeline on the dashboard", "Evaluate alternative material market share", "Publish plastic ban policy brief"] },
    { title: "Urban Land Degradation and Landslides Nexus", steps: ["Download hillside slope erosion and development logs from environmentdash.lovable.app", "Map slope quarrying and illegal constructions", "Correlate building density with landslide frequency on the dashboard", "Model forest cover stabilization benefits", "Publish landslide hazard zoning study"] },
  ],
  "sound-pollution": [
    { title: "Noise Pollution Exposure Research", steps: ["Export decibel monitoring series from environmentdash.lovable.app", "Calculate percentage of population exposed to high noise levels", "Map chronic noise exposure zones on the dashboard", "Assess correlation with sleep disturbance reports", "Write urban noise exposure research paper"] },
    { title: "Occupational Noise Hearing Loss Study", steps: ["Download audiometry survey records of industrial workers from environmentdash.lovable.app", "Map hearing threshold shifts against factory noise profiles", "Analyze protective earplug compliance rates on the dashboard", "Evaluate rehabilitation funding access", "Publish occupational hearing loss research"] },
    { title: "Urban Park Acoustic Tranquility Index", steps: ["Extract city park decibel logs and bird biodiversity metrics from environmentdash.lovable.app", "Calculate acoustic tranquility scores for urban parks", "Map sound dampening effect of park vegetation on the dashboard", "Correlate indices with visitor density", "Publish urban park acoustic paper"] },
    { title: "Traffic Noise Wall Cost-Benefit Analysis", steps: ["Download city noise wall construction costs from environmentdash.lovable.app", "Map high-decibel highway corridors adjacent to schools", "Model decibel reduction vs construction investment on the dashboard", "Compare metal vs concrete wall barriers", "Draft highway acoustic barrier recommendations"] },
    { title: "No-Honking Policy Enforcement Evaluation", steps: ["Download municipal honking sensor logs before and after 'No-Honking Day' from environmentdash.lovable.app", "Compare decibel levels during enforcement campaign", "Analyze penalty citation distribution on the dashboard", "Evaluate driver behavior change index", "Publish honking policy evaluation report"] },
  ],
  transportation: [
    { title: "Transport Accessibility Research", steps: ["Collect rail, road, and airport access data", "Calculate district accessibility scores", "Map underserved regions", "Compare with economic indicators", "Write research report"] },
    { title: "Road Safety Risk Research", steps: ["Use crash and traffic volume data", "Calculate fatality risk indicators", "Identify black spot clusters", "Compare enforcement and infrastructure factors", "Publish safety recommendations"] },
    { title: "Public Transport Equity Study", steps: ["Collect ridership and route coverage data", "Compare access across city zones", "Identify underserved communities", "Assess affordability indicators", "Prepare policy note"] },
    { title: "Freight Efficiency Research", steps: ["Merge freight movement and infrastructure data", "Compare rail, road, and port flows", "Identify bottleneck corridors", "Calculate logistics efficiency indicators", "Write research summary"] },
    { title: "EV Infrastructure Readiness Study", steps: ["Download EV and charging station data", "Calculate station density by state", "Compare with vehicle registration trends", "Identify readiness gaps", "Publish clean mobility brief"] },
  ],
  "smart-cities": [
    { title: "Smart City Governance Research", steps: ["Collect mission progress and governance indicators", "Compare city implementation rates", "Identify high-performing models", "Analyze service delivery outcomes", "Write research report"] },
    { title: "Urban Service Equity Study", steps: ["Use water, waste, and grievance data", "Map ward-level service gaps", "Compare vulnerable zones", "Identify equity priorities", "Prepare policy recommendations"] },
    { title: "Digital Urban Inclusion Research", steps: ["Collect public Wi-Fi and digital payment data", "Compare city-tier adoption", "Identify digital access gaps", "Correlate with service usage", "Publish inclusion findings"] },
    { title: "Smart Mobility Impact Study", steps: ["Use smart bus, parking, and traffic datasets", "Measure congestion and ridership changes", "Compare cities by mobility outcomes", "Identify scalable interventions", "Write research-grade summary"] },
    { title: "Urban Resilience Research Index", steps: ["Select heat, water, waste, and infrastructure indicators", "Normalize city-level resilience scores", "Rank cities by preparedness", "Map priority improvement areas", "Document methodology"] },
  ],
};

export const PROJECT_LEVELS: ProjectLevel[] = ["Medium", "High", "Extreme High", "Research"];

const DATA_USED_BY_DOMAIN: Record<string, string> = {
  population: "Census India population tables and state-wise dashboard exports",
  crime: "NCRB crime statistics, district records, and safety indicators",
  education: "Census literacy tables, district literacy indicators, gender-gap data, and rural-urban literacy statistics",
  healthcare: "NFHS, HMIS, NHP, NIKSHAY, CoWIN, and public health facility data",
  agriculture: "ICAR, IMD rainfall, Agmarknet, PMFBY, soil health, and crop production data",
  economy: "MoSPI, RBI, GSTN, DPIIT, NPCI, CAG, and state finance data",
  employment: "PLFS, NSSO, PMKVY, MGNREGS, e-Shram, and labour market data",
  environment: "CPCB, IMD, FSI, CGWB, MNRE, and environmental monitoring data",
  climate: "IMD rainfall and temperature records, extreme weather events, drought, flood, and climate risk indicators",
  energy: "POSOCO, MNRE, CEA, DISCOM, smart meter, renewable capacity, and power reliability data",
  pollution: "CPCB, SPCB, CGWB, river quality, AQI, waste, noise, and industrial compliance data",
  "pollution-all": "CPCB, SPCB, CGWB, SBM, river quality, AQI, noise, and waste data",
  "wind-pollution": "CPCB, SPCB, AQI, vehicle emissions, and dust pollution data",
  "water-pollution": "CPCB, CGWB, NCCR, river quality, coastal, and groundwater data",
  "land-pollution": "CPCB, SBM, solid waste, plastic, hazardous, and landfill data",
  "sound-pollution": "CPCB, SPCB city decibel monitoring data and noise levels",
  transportation: "Indian Railways, NHAI, MORTH, VAHAN, AAI, IWAI, and mobility data",
  "smart-cities": "Smart Cities Mission, MoHUA, AMRUT, PM-WANI, and city service data",
};

function levelForIndex(index: number): ProjectLevel {
  if (index < 5) return "Medium";
  if (index < 10) return "High";
  return "Extreme High";
}

export const PROJECTS: Record<string, Project[]> = Object.fromEntries(
  Object.entries(raw).map(([domain, projects]) => [
    domain,
    [
      ...projects.map((p, index) => ({
        ...p,
        level: levelForIndex(index),
        dataUsed: DATA_USED_BY_DOMAIN[domain],
        slug: toSlug(p.title)
      })),
      ...(research[domain] ?? []).map(p => ({
        ...p,
        level: "Research" as ProjectLevel,
        dataUsed: DATA_USED_BY_DOMAIN[domain],
        slug: toSlug(p.title)
      }))
    ]
  ])
);

PROJECTS["pollution-all"] = [
  ...(PROJECTS["wind-pollution"] ?? []),
  ...(PROJECTS["water-pollution"] ?? []),
  ...(PROJECTS["land-pollution"] ?? []),
  ...(PROJECTS["sound-pollution"] ?? []),
].map(p => ({
  ...p,
  dataUsed: DATA_USED_BY_DOMAIN["pollution-all"] ?? p.dataUsed
}));
